spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    register-with-eurka: false
    fetch-registry: false

server:
  port: 8761
