spring:
  application:
    name: eureka-server
  cloud:
    config:
      service-url:
        defaultZone: http://localhost:8761/eureka/
eureka:
  client:
    register-with-eurka: false
    fetch-registry: false

server:
  port: 8761
